coralogix/arrow-ballista

.github/workflows/dev.yml
ballista/rust/core/src/config.rs
ballista/rust/core/src/serde/physical_plan/mod.rs
ballista/rust/scheduler/src/scheduler_server/event_loop.rs

Fix bug in physical plan serialization when we have an empty list of group by expressions.

Fix bug in physical plan serialization

---

ballista/rust/core/proto/ballista.proto
ballista/rust/scheduler/src/main.rs
ballista/rust/scheduler/src/scheduler_server/event.rs
ballista/rust/scheduler/src/scheduler_server/event_loop.rs
ballista/rust/scheduler/src/scheduler_server/grpc.rs
ballista/rust/scheduler/src/scheduler_server/metrics/mod.rs
ballista/rust/scheduler/src/scheduler_server/mod.rs
ballista/rust/scheduler/src/scheduler_server/query_stage_scheduler.rs
ballista/rust/scheduler/src/standalone.rs
ballista/rust/scheduler/src/state/execution_graph.rs
ballista/rust/scheduler/src/state/task_manager.rs

Add `SchedulerMetricsCollector` which gives ability to collect basic metrics about jobs.

Scheduler metrics

---

ballista/rust/core/src/execution_plans/shuffle_writer.rs
ballista/rust/scheduler/src/scheduler_server/grpc.rs

Log the execution plan when a shuffle write fails for better debugging. 
Also handle a few places where we were panicing instead of properly handling errors.

Better logging on job failures

---

ballista/rust/scheduler/src/state/task_manager.rs

Fail jobs instead of rescheduling on executor lost event

sc-10300: fail running jobs

---

ballista/rust/core/src/execution_plans/distributed_query.rs
ballista/rust/scheduler/src/state/task_manager.rs

Fixes executor lost handling (I hope). 
The previous approach was calling `fail_running_job` which somewhat confusingly doesn't actually do what we want. The executor has an in-memory cache that needs to be updated. Without updating the cache, the job is permanently stuck in a queued state.

Fix bug in executor lost handling

---

ballista/rust/scheduler/src/scheduler_server/external_scaler.rs
ballista/rust/scheduler/src/state/mod.rs
ballista/rust/scheduler/src/state/task_manager.rs

sc-5792: pending queue variable

---

ballista/scheduler/src/scheduler_server/mod.rs

Expose alive executors

---

ballista/core/Cargo.toml
ballista/core/src/execution_plans/shuffle_reader.rs

This is expected to happen sometimes and is polluting out error alerts. Decreasing to warning

Downgrade expected error to warning

---

ballista/scheduler/src/scheduler_server/mod.rs
ballista/scheduler/src/state/executor_manager.rs
ballista/scheduler/src/state/mod.rs

* Mark as pub
* Fmt
---------
Closes #.

Mark `SchedulerState` as pub (#688)

---

ballista/core/src/serde/scheduler/from_proto.rs
ballista/executor/src/execution_engine.rs
ballista/executor/src/executor_server.rs

Cherry-pick decode_once changes from upstream ballista

---

ballista/core/src/execution_plans/distributed_query.rs
ballista/executor/src/collect.rs
ballista/scheduler/src/state/execution_graph.rs

Attempt to remove error wrapping that prevents us from receiving clear external error

VTX-522: remove some errors wrappings

---

Cargo.toml
ballista-cli/Cargo.toml
ballista/client/Cargo.toml
ballista/client/src/context.rs
ballista/core/Cargo.toml
ballista/core/src/serde/generated/ballista.rs
ballista/core/src/serde/scheduler/mod.rs
ballista/core/src/utils.rs
ballista/executor/Cargo.toml
ballista/scheduler/Cargo.toml
ballista/scheduler/scheduler_config_spec.toml
ballista/scheduler/src/flight_sql.rs
ballista/tests/Cargo.toml
examples/Cargo.toml

Update to DataFusion 24

---

ballista/core/src/client.rs

The comment was right and the number was wrong :(

Set limit to 16MiB instead of 16GiB

---

ballista/core/src/physical_optimizer/task_group.rs

[VTX-1185]
[VTX-1185]: https://coralogix.atlassian.net/browse/VTX-1185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Push down `HashJoinExec` inside `CoalesceTasksExec`

---

ballista/scheduler/src/cluster/memory.rs
ballista/scheduler/src/state/task_manager.rs

Storing execution graph both in running jobs and completed

VTX-1683: store more info about running jobs in memory job state

---

ballista/core/src/physical_optimizer/task_group.rs

Try and fix and cleanup the optimizer. I think it was not handling reduce tasks correctly and we mostly avoided nastiness by dumb luck....

Fix some issues in the OptimizeTaskGroups optimizer

---

Cargo.toml
ballista/client/README.md
ballista/core/proto/ballista.proto
ballista/core/src/error.rs
ballista/core/src/execution_plans/coalesce_tasks.rs
ballista/core/src/execution_plans/distributed_query.rs
ballista/core/src/execution_plans/shuffle_reader.rs
ballista/core/src/execution_plans/shuffle_writer.rs
ballista/core/src/execution_plans/unresolved_shuffle.rs
ballista/core/src/physical_optimizer/task_group.rs
ballista/core/src/serde/generated/ballista.rs
ballista/core/src/utils.rs
ballista/executor/src/collect.rs
ballista/executor/src/execution_engine.rs
ballista/executor/src/execution_loop.rs
ballista/executor/src/executor.rs
ballista/executor/src/executor_server.rs
ballista/scheduler/benches/scheduler_events.rs
ballista/scheduler/src/flight_sql.rs
ballista/scheduler/src/planner.rs
ballista/scheduler/src/state/execution_graph.rs
ballista/scheduler/src/state/execution_graph/execution_stage.rs
ballista/scheduler/src/state/execution_graph_dot.rs
ballista/scheduler/src/state/mod.rs
ballista/scheduler/src/test_utils.rs
ballista/tests/src/test_table_exec.rs
benchmarks/src/bin/tpch.rs

Update to datafusion 28

---

Cargo.toml

Update to 28

---

Cargo.toml
ballista/core/proto/ballista.proto
ballista/core/src/lib.rs
ballista/core/src/serde/generated/ballista.rs
ballista/core/src/serde/scheduler/to_proto.rs
ballista/executor/src/execution_loop.rs
ballista/executor/src/executor_server.rs
ballista/scheduler/Cargo.toml
ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs
ballista/scheduler/src/state/execution_graph.rs
ballista/scheduler/src/state/execution_graph/execution_stage.rs
ballista/scheduler/src/state/mod.rs
ballista/scheduler/src/state/task_manager.rs
ballista/tests/src/test_table_exec.rs

[VTX-2906]
Add a metric for time tasks spend ready to be scheduled. 
[VTX-2906]: https://coralogix.atlassian.net/browse/VTX-2906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add metric for task idle time

---

ballista/core/src/execution_plans/coalesce_tasks.rs

I've tested and this is the only reason we don't have spans propagating into e.g. OpenSearchIndexScan.

Fix span propagation in CoalesceTasksExec

---

ballista/core/src/execution_plans/coalesce_tasks.rs

@thinkharderdev accidentally reverted too much when he removed the coalesce_tasks span, removing the tracing propagation in the process.

Unrevert spans propagation

---

ballista/core/src/client.rs

Allow handling of streams with Dictionary encoding.

Use FlightRecordBatchStream correctly

---

ballista/core/proto/datafusion.proto

Update DataFusion proto

---

ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs
ballista/scheduler/src/state/executor_manager.rs

To avoid grpc calls directly from event loop

Spawn cancel_running_tasks

---

ballista/core/src/serde/scheduler/mod.rs

Fix executor endpoint

---

ballista/scheduler/src/state/execution_graph/execution_stage.rs

Optimize count based on resolved statistics

---

Cargo.toml

Update DataFusion tag

---

Cargo.toml

Closes #8461.
dict_id is there, we should serde it
Add dict_id to serde
v3 queries should work

Update datafusion to serde dict_id

---

Cargo.toml
ballista/client/src/columnar_batch.rs
ballista/client/src/context.rs
ballista/scheduler/src/scheduler_server/grpc.rs
benchmarks/src/bin/tpch.rs

Update DataFusion to latest again

---

ballista/executor/src/executor.rs

[VTX-3855]
Just adding a hook to be able to cancel all running tasks. Remainder of this will be in DQE
[VTX-3855]: https://coralogix.atlassian.net/browse/VTX-3855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add hook to cancel all running tasks on executor

---

ballista/executor/Cargo.toml
ballista/executor/src/executor.rs
ballista/executor/src/executor_server.rs
ballista/executor/src/lib.rs

[VTX-3874]
Handle situation in which we can't send scheduler lost:
1. Retry for longer (up to 30s) to try and "wait out" new schedulers becoming available
2. If that fails, self-terminate
[VTX-3874]: https://coralogix.atlassian.net/browse/VTX-3874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Schedulers unavailable

---

ballista/core/src/execution_plans/shuffle_reader.rs
ballista/core/src/execution_plans/shuffle_writer.rs
ballista/core/src/utils.rs
ballista/executor/src/flight_service.rs
ballista/executor/src/replicator/mod.rs

Closes #.
We need to support dictionaries now with v3 & JSONA.
Switch from FileWriter to StreamWriter
Hopefully v3 queries work more often

Switch to StreamWriter/Reader

---

ballista/core/src/execution_plans/shuffle_writer.rs
ballista/core/src/replicator/mod.rs
ballista/executor/src/replicator/mod.rs

To better understand replicator behavior I want to have a lag latency metric

VTX-3411: track replication lag latency

---

Cargo.toml
ballista/core/src/execution_plans/shuffle_reader.rs
ballista/core/src/execution_plans/shuffle_writer.rs
ballista/core/src/physical_optimizer/task_group.rs
ballista/core/src/utils.rs
ballista/executor/src/flight_service.rs
ballista/executor/src/replicator/mod.rs

Update to DF 34 release version, update master

---

Cargo.toml
ballista/core/Cargo.toml
ballista/core/src/execution_plans/shuffle_reader.rs
ballista/executor/Cargo.toml
ballista/tests/Cargo.toml

VTX-3411: more metrics

---

ballista/executor/src/replicator/mod.rs

We should always abort failed multipart uploads to avoid paying for the s3 storage, also we should count the number of written bytes only in case of success, as it shows a misleading pictures in a Grafana dashboard

VTX-3411: abort failed upload, update metrics

---

ballista/executor/src/replicator/mod.rs

Remove double metric incrementation in case of an empty file

VVTX-3411: remove double increment

---

Cargo.toml
ballista/core/Cargo.toml
ballista/core/src/execution_plans/shuffle_reader.rs
ballista/core/src/execution_plans/shuffle_writer.rs
ballista/core/src/replicator/mod.rs
ballista/executor/Cargo.toml
ballista/executor/src/replicator/mod.rs
ballista/scheduler/src/cluster/storage/etcd.rs
ballista/tests/Cargo.toml

Update master to include latest changes

---

ballista/core/src/execution_plans/shuffle_reader.rs
ballista/executor/src/flight_service.rs

Add some more logging around shuffle operations

Add some logging to shuffle operation

---

ballista/core/src/execution_plans/shuffle_reader.rs
ballista/executor/src/flight_service.rs

Add some logging around the shuffle process

Add some logging to help debug slow shuffles

---

ballista/scheduler/src/state/execution_graph.rs
ballista/scheduler/src/state/task_manager.rs
ballista/tests/proto/logical_plan.proto
ballista/tests/proto/physical_plan.proto
ballista/tests/src/lib.rs
ballista/tests/src/proto.rs
ballista/tests/src/test_table.rs
ballista/tests/src/test_table_exec.rs

This ensures that the two circuit breakers do in fact operate independently from one another.

Add a test for two circuit breakers inside of a union

---

ballista/core/src/execution_plans/shuffle_reader.rs

VTX-3411: small update

---

.gitignore
Cargo.toml
ballista/core/proto/ballista.proto
ballista/core/src/execution_plans/coalesce_tasks.rs
ballista/core/src/execution_plans/shuffle_writer.rs
ballista/core/src/physical_optimizer/task_group.rs
ballista/core/src/serde/generated/ballista.rs
ballista/core/src/serde/mod.rs
ballista/executor/src/executor.rs

Order-aware coalesce task operator

VTX-4075: order aware coalesce

---

ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs
ballista/scheduler/src/state/execution_graph.rs
ballista/scheduler/src/state/execution_graph/execution_stage.rs
ballista/scheduler/src/state/mod.rs
ballista/scheduler/src/state/task_manager.rs

[VTX-3877]
We want to test priority based scheduling against vanilla scheduling. 
Closes #.
[VTX-3877]: https://coralogix.atlassian.net/browse/VTX-3877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

VTX-3877 revert priority based scheduling

---

ballista/scheduler/src/state/execution_graph.rs
ballista/scheduler/src/state/task_manager.rs

Fix regression from the last [PR](https://github.com/coralogix/arrow-ballista/pull/178/files)

VTX-4445: remove failed jobs without running tasks

---

Cargo.toml
ballista/core/Cargo.toml
ballista/core/proto/ballista.proto
ballista/core/src/async_reader/mod.rs
ballista/core/src/execution_plans/mod.rs
ballista/core/src/execution_plans/shuffle_reader.rs
ballista/core/src/physical_optimizer/task_group.rs
ballista/core/src/serde/generated/ballista.rs
ballista/core/src/serde/mod.rs
ballista/executor/src/executor_process.rs
ballista/executor/src/flight_service.rs
ballista/executor/src/replicator/mod.rs
ballista/executor/src/standalone.rs
ballista/scheduler/benches/scheduler_events.rs
ballista/scheduler/src/bin/main.rs
ballista/scheduler/src/planner.rs
ballista/scheduler/src/scheduler_process.rs
ballista/scheduler/src/scheduler_server/grpc.rs
ballista/scheduler/src/scheduler_server/mod.rs
ballista/scheduler/src/standalone.rs
ballista/scheduler/src/state/execution_graph.rs
ballista/scheduler/src/state/execution_graph/execution_stage.rs
ballista/scheduler/src/state/execution_graph_dot.rs
ballista/scheduler/src/state/mod.rs
ballista/scheduler/src/state/task_manager.rs
ballista/scheduler/src/test_utils.rs

Expose more params as env variable, using async streams + async readers to accommodate streaming without buffering overhead

VTX-4537: more params exposed as env var

---

ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs
ballista/scheduler/src/state/execution_graph.rs
ballista/scheduler/src/state/execution_graph/execution_stage.rs
ballista/scheduler/src/state/mod.rs
ballista/scheduler/src/state/task_manager.rs

This reverts commit b0b836d393ba9c19420c44730c640428166ff56c.
Closes [VTX-3877].
[VTX-3877]: https://coralogix.atlassian.net/browse/VTX-3877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "VTX-3877 Priority-based Scheduling (#186)"

---

ballista/core/src/client.rs
ballista/core/src/execution_plans/shuffle_reader.rs
ballista/core/src/serde/scheduler/mod.rs

VTX-4537: revert port changes

---

ballista/core/src/async_reader/mod.rs
ballista/core/src/execution_plans/shuffle_reader.rs
ballista/executor/src/flight_service.rs
ballista/executor/src/replicator/mod.rs

Labeled async stream with duration latency reporting

VTX-4537: add metrics to async stream

---

ballista/core/src/execution_plans/shuffle_writer.rs

VTX-4537: shuffle size metrics
