ballista/rust/scheduler/src/state/executor_manager.rs
Use correct keyspace for heartbeat initialisation when starting scheduler
=> Use correct keyspace when initing heartbeats

ballista/rust/executor/src/executor_server.rs, ballista/rust/scheduler/src/state/execution_graph.rs, ballista/rust/scheduler/src/state/task_manager.rs
Make sure we catch any panics during task execution so we can properly report task failures to the scheduler. This uses the same approach that was already implemented for pull-based scheduling. 
Also add some additional logging to help debug scheduler issues
=> Catch panics in task execution so jobs do not hang

ballista/rust/core/Cargo.toml, ballista/rust/core/proto/ballista.proto, ballista/rust/core/src/execution_plans/shuffle_writer.rs, ballista/rust/core/src/serde/physical_plan/mod.rs, ballista/rust/core/src/utils.rs, ballista/rust/executor/src/executor.rs, ballista/rust/executor/src/executor_server.rs, ballista/rust/scheduler/src/planner.rs, ballista/rust/scheduler/src/scheduler_server/external_scaler.rs, ballista/rust/scheduler/src/state/mod.rs, ballista/rust/scheduler/src/state/task_manager.rs
This is very hacky and completely untested but the basic setup should work I think. The hard part is managing the lifecycle of the accumulators since we don't really have a good way of removing them when they are no longer needed. I've hand-waved that problem away by just tossing them in an LRU cache so we at least don't leak memory in an unbounded way.
=> Use node-level local limit

ballista/rust/scheduler/src/scheduler_server/external_scaler.rs, ballista/rust/scheduler/src/scheduler_server/mod.rs, ballista/rust/scheduler/src/state/execution_graph.rs, ballista/rust/scheduler/src/state/task_manager.rs
To correctly calculate the counter of pending tasks, we need to track the number of newly converted tasks from the revive method.
So right now we increasing the pending queue size:
- submit new job
- revive
- update job
And decreasing it:
- filling reservation for task
- fail job
- cancel job
=> Expose pending queue size metric

ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/task_manager.rs
[sc-16524]
We were not removing cancelled jobs from the active cache which was causing warnings in the log and also a memory leak
=> Remove cancelled jobs from active cache

ballista-cli/Cargo.toml, ballista/client/Cargo.toml, ballista/core/Cargo.toml, ballista/core/proto/ballista.proto, ballista/core/src/serde/generated/ballista.rs, ballista/executor/Cargo.toml, ballista/executor/src/execution_loop.rs, ballista/executor/src/executor_process.rs, ballista/executor/src/executor_server.rs, ballista/executor/src/standalone.rs, ballista/scheduler/Cargo.toml, ballista/scheduler/src/cluster/kv.rs, ballista/scheduler/src/cluster/memory.rs, ballista/scheduler/src/cluster/mod.rs, ballista/scheduler/src/flight_sql.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/mod.rs, ballista/scheduler/src/standalone.rs, ballista/scheduler/src/state/mod.rs, ballista/scheduler/src/state/session_manager.rs, ballista/scheduler/src/state/task_manager.rs, ballista/scheduler/src/test_utils.rs, benchmarks/Cargo.toml, examples/Cargo.toml
- add serialization of configoptions
- pass them to executors
- reconstruct configoptions on executors
- requires https://github.com/coralogix/arrow-datafusion/tree/allow-extensions-in-taskcontext
=> Serialize configoptions and pass them to executor

ballista/core/src/execution_plans/shuffle_reader.rs, ballista/executor/src/executor.rs, ballista/executor/src/executor_process.rs, ballista/scheduler/src/cluster/event/mod.rs, ballista/scheduler/src/scheduler_server/mod.rs, ballista/scheduler/src/state/task_manager.rs, ballista/scheduler/src/test_utils.rs
Add wait_drained to SchedulerServer and Executor which returns future which completes when active jobs/tasks reaches 0.
=> Add wait_drained to SchedulerServer and Executor

ballista/scheduler/src/display.rs, ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/execution_graph/execution_stage.rs
=> Do not fail task update when metrics array has wrong length

ballista/scheduler/src/metrics/mod.rs, ballista/scheduler/src/metrics/prometheus.rs, ballista/scheduler/src/scheduler_server/event.rs, ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs, ballista/scheduler/src/test_utils.rs
Add some additional metrics from scheduler:
1. Event processing time to measure how long it takes to process `QueryStageSchedulerEvents` 
2. Counter for event processing failures.
=> Additional scheduler metrics

.github/workflows/rust.yml, ballista/core/proto/ballista.proto, ballista/core/src/error.rs, ballista/core/src/execution_plans/distributed_query.rs, ballista/core/src/execution_plans/shuffle_writer.rs, ballista/core/src/serde/generated/ballista.rs, ballista/scheduler/Cargo.toml, ballista/scheduler/src/cluster/kv.rs, ballista/scheduler/src/cluster/memory.rs, ballista/scheduler/src/scheduler_server/event.rs, ballista/scheduler/src/scheduler_server/mod.rs, ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/execution_graph/execution_stage.rs, ballista/scheduler/src/state/task_manager.rs, ballista/tests/Cargo.toml, ballista/tests/src/proto.rs, ballista/tests/src/test_logical_codec.rs, ballista/tests/src/test_table_exec.rs
In this PR I'm trying to use the newly introduced `execution_error` as a general error across the codebase
we had a few rudimental wrapping which caused some issues, they were removed
=> VTX-522: use execution error as a base error object

ballista/executor/src/cpu_bound_executor.rs, ballista/executor/src/executor_server.rs, ballista/executor/src/flight_service.rs, ballista/scheduler/src/state/execution_graph.rs
[VTX-1203]
Switch the executor flight server to use `FlightDataEncoder` from `arrow-rs` which already handles splitting batches to ensure a max gRPC message size. 
[VTX-1203]: https://coralogix.atlassian.net/browse/VTX-1203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> User FlightDataEncoder from arrow-rs

ballista/executor/src/executor.rs, ballista/executor/src/executor_process.rs, ballista/executor/src/executor_server.rs, ballista/executor/src/flight_service.rs, ballista/executor/src/standalone.rs
[VTX-1189]
If the executor is not able to report some sort of task status for a task it has been assigned then there is no way for the task slots to be freed. This PR ensures that in all error scenarios we still send a task status back to the scheduler. 
I also went through and cleaned up a lot of the logging:
1. Use attributes wherever we can to create useful searchable fields 
2. Log the executor ID wherever we have it in scope so we can drill down on a particular executor in the logs when all we have is the ID (from the scheduler logs for example). 
[VTX-1189]: https://coralogix.atlassian.net/browse/VTX-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Always handle errors in task runner and improve logging

ballista/executor/src/executor_server.rs, ballista/scheduler/benches/scheduler_events.rs, ballista/scheduler/src/circuit_breaker/controller.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/mod.rs, ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs, ballista/scheduler/src/state/mod.rs, ballista/scheduler/src/state/task_manager.rs, ballista/scheduler/src/test_utils.rs
[VTX-768]
Currently when the scheduler fails to launch a task (gRPC call to executor fails, etc) then those tasks will be forever stuck in running state and the job will hang indefinitely. 
With this update if we fail to launch then a synthetic task status will get generated so the tasks can be rescheduled. 
With that in place we can solve another issue where we have a sort of race condition. When the executor goes into terminating state and has no pending tasks it will go immediately into it's 30s shutdown wait. But between the time the executor goes into terminating status and the scheduler actually receives that status, the executor can have new tasks assigned. Since we can now handle task launch failures, as soon as the executor goes into `TERMINATING` status, it will start rejecting …
=> Handle task launch failures

ballista/core/proto/ballista.proto, ballista/core/src/serde/generated/ballista.rs, ballista/executor/src/executor_server.rs, ballista/scheduler/benches/scheduler_events.rs, ballista/scheduler/src/scheduler_server/event.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/mod.rs, ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs, ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/mod.rs, ballista/scheduler/src/test_utils.rs
Previous commit changed the executor behavior so it starts rejecting tasks once it goes into terminating state. That causes a downstream issue since when the scheduler fails to launch a task it will re-offer those reservations to it's event loop. At that point there is nothing to check whether the executor is still alive so it will get new tasks assigned, those tasks will again fail to launch and it will go into a more-or-less infinite loop. 
With this change we just return the executor slots to the global pool instead of re-offering them to the event loop. In that case they will be returned and since the executor is already in terminating state, the slots will never be reassigned and eventually removed. In the case where the task launching was some spurious failure this adds some extra …
=> Fix for terminating executors

ballista/core/src/error.rs, ballista/core/src/serde/generated/ballista.rs
Mark arrow external error as an error that can be returned back to the user
=> VTX-1274: show arrow external error back to user

Cargo.toml
[VTX-1125]
In order to bring in additions for timestamp and interval arithmetic in Datafusion
https://github.com/apache/arrow-datafusion/blob/main/dev/changelog/25.0.0.md
[VTX-1125]: https://coralogix.atlassian.net/browse/VTX-1125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update arrow and datafusion

ballista/core/proto/ballista.proto, ballista/core/src/serde/generated/ballista.rs, ballista/scheduler/src/api/handlers.rs, ballista/scheduler/src/cluster/kv.rs, ballista/scheduler/src/cluster/memory.rs, ballista/scheduler/src/cluster/mod.rs, ballista/scheduler/src/cluster/test/mod.rs, ballista/scheduler/src/scheduler_server/event.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs, ballista/scheduler/src/state/task_manager.rs
Generally, we would like to be able to store `JobOverview` in Redis, so I moved the definition to proto, to exploit serialization later in DQE
Minor:
- update `submit_job` method signature
- add more useful info to `fail_unscheduled_job` to avoid additional lookup
=> VTX-1684: Update JobOverview

Cargo.toml, ballista/core/src/plugin/mod.rs, ballista/core/src/serde/scheduler/to_proto.rs
Closes #4883. (in arrow-rs)
Users want to be able to sort RecordBatches with Unions in them.
Ability to sort RecordBatches with Unions.
Sorting with Unions should work.
=> upgrade to arrow-rs with take support for unions

ballista/core/src/serde/scheduler/to_proto.rs, ballista/executor/src/circuit_breaker/client.rs, ballista/executor/src/execution_loop.rs, ballista/executor/src/executor_server.rs, ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/mod.rs, ballista/scheduler/src/state/task_manager.rs
Also fixes clippy warnings.
I'm seeing some very slow update requests (> 1s) during testing in cx180. Although even the 99th percentile is only ~50ms, I want to experiment with less frequent and more efficient updates.
The old implementation reads a batch of updates from the channel (with a max duration and a max size). It deduplicates by task ID, then sends the updates to the respective schedulers.
If we want to decrease the frequency, the old implementation will start hitting the batch size and not the duration limit.
The actual number of updates sent to each scheduler will still vary wildly, due to the deduplication and the global limit of messages as opposed to a per-scheduler one.
The new implementation will only hit the batch size limit on a per-scheduler basis, and not counting …
=> Improve circuit breaker client

ballista/core/src/execution_plans/coalesce_tasks.rs
[VTX-2935]
This is creating too many spans, making traces unusable 
[VTX-2935]: https://coralogix.atlassian.net/browse/VTX-2935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert noisy spans

ballista/core/proto/ballista.proto, ballista/core/src/circuit_breaker/model.rs, ballista/core/src/serde/generated/ballista.rs, ballista/scheduler/src/circuit_breaker/controller.rs, ballista/tests/src/test_table_exec.rs
We need support for shared circuit breaker state across stages, so we can apply a single byte scan limit to union queries.
This change adds support for a custom shared state key (that can be set to the stage ID if no sharing is needed).
It should also handle attempts correctly by always using the latest attempt of each stage for the calculation.
Follow-up change in DQE: https://github.com/coralogix/dataprime-query-engine/pull/1603
=> Circuit breaker cross stage state

Cargo.toml, ballista/executor/src/flight_service.rs
So`FetchPartition` will use lz4 compression instead of sending the data uncompressed.
Should also reduce the chance we send a batch bigger than the max message size (even though there is no guarantee for e.g. huge rows).
=> Enable flight stream lz4 compression

ballista/core/src/serde/scheduler/mod.rs, ballista/scheduler/src/state/executor_manager.rs
- Cache executor client by host:port
- Remove executor client when deregistering executor
=> Cache executor client by host:port

ballista/scheduler/src/state/executor_manager.rs
Executor metadata might be already removed before scheduler has a chance to remove executor client which results in error.
=> Fix executor removal errors

ballista/core/proto/ballista.proto, ballista/core/src/execution_plans/shuffle_reader.rs, ballista/core/src/physical_optimizer/task_group.rs, ballista/core/src/serde/generated/ballista.rs, ballista/core/src/serde/scheduler/from_proto.rs, ballista/core/src/serde/scheduler/mod.rs, ballista/core/src/serde/scheduler/to_proto.rs, ballista/executor/executor_config_spec.toml, ballista/executor/src/bin/main.rs, ballista/executor/src/executor_process.rs, ballista/executor/src/standalone.rs, ballista/scheduler/benches/scheduler_events.rs, ballista/scheduler/src/cluster/test/mod.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/mod.rs, ballista/scheduler/src/state/executor_manager.rs, ballista/scheduler/src/state/mod.rs, ballista/scheduler/src/test_utils.rs, ballista/tests/src/lib.rs
Introducing version-aware schedulers. Executors can be registered with a version string.
Closes #.
=> VTX-3322 Register executor version

ballista/core/proto/ballista.proto, ballista/core/src/serde/generated/ballista.rs, ballista/executor/src/circuit_breaker/client.rs, ballista/executor/src/circuit_breaker/stream.rs, ballista/scheduler/src/circuit_breaker/controller.rs, ballista/scheduler/src/scheduler_server/event.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs, ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/mod.rs, ballista/scheduler/src/state/task_manager.rs, ballista/tests/src/lib.rs, ballista/tests/src/test_table_exec.rs
Add labels that can be defined during registration of a task with circuit breaker. This way, one can later determine which circuit breaker was tripped by looking at the job status.
=> Add labels to circuit breaker

ballista/core/src/execution_plans/shuffle_reader.rs, ballista/core/src/execution_plans/shuffle_writer.rs
During monitoring async replication I discovered that we're creating a lot of empty batches/files. I think with this simple check we can reduce the amount of useless work
=> VTX-3411: do not write empty batches

ballista/core/proto/ballista.proto, ballista/core/src/circuit_breaker/model.rs, ballista/core/src/serde/generated/ballista.rs, ballista/executor/src/circuit_breaker/client.rs, ballista/executor/src/circuit_breaker/stream.rs, ballista/scheduler/src/circuit_breaker/controller.rs, ballista/scheduler/src/scheduler_server/event.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/query_stage_scheduler.rs, ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/task_manager.rs, ballista/tests/src/test_table_exec.rs
We do not want to preempt the stage (mark all pending tasks as completed) in case of circuit breaker used for limit execs, only when it is used to enforce a scan limit. So I've made it configurable.
Also rename `...StageKey` stuff to `...StateKey` because we have a state ID there, too, so there are possibly several different ones per stage.
[VTX-4079]
[VTX-4079]: https://coralogix.atlassian.net/browse/VTX-4079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Configurable stage preemption in circuit breaker

ballista/core/src/execution_plans/shuffle_reader.rs, ballista/core/src/execution_plans/shuffle_writer.rs, ballista/core/src/utils.rs, ballista/executor/src/replicator/mod.rs
[VTX-3411]
More aggressive skipping of empty files for replication, special handling in case of s3 key not found error
[VTX-3411]: https://coralogix.atlassian.net/browse/VTX-3411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VTX-3411: skip empty files more aggressively, wrap not found an error

ballista/executor/src/replicator/mod.rs
After the upgrade we accidentally brought back what was fixed here: https://github.com/coralogix/arrow-ballista/pull/159
=> VTX-3411: metrics fix

ballista/core/src/execution_plans/shuffle_reader.rs
Skip empty partitions in the shuffle reader
=> VTX-3411: skip empty partitions in shuffle reader

ballista/scheduler/src/cluster/memory.rs, ballista/scheduler/src/state/task_manager.rs
So we can keep completed jobs around for longer, we drop the `ExecutionGraph` once it's completed
=> Drop execution graph when job is completed

ballista/core/proto/ballista.proto, ballista/core/src/execution_plans/shuffle_reader.rs, ballista/core/src/physical_optimizer/task_group.rs, ballista/core/src/serde/generated/ballista.rs, ballista/core/src/serde/mod.rs, ballista/executor/src/flight_service.rs, ballista/scheduler/benches/scheduler_events.rs, ballista/scheduler/src/bin/main.rs, ballista/scheduler/src/planner.rs, ballista/scheduler/src/scheduler_process.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/mod.rs, ballista/scheduler/src/standalone.rs, ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/execution_graph/execution_stage.rs, ballista/scheduler/src/state/execution_graph_dot.rs, ballista/scheduler/src/state/mod.rs, ballista/scheduler/src/state/task_manager.rs, ballista/scheduler/src/test_utils.rs
Switching to async stream readers for `do_get` endpoint. Also increased flight-service stream return channel size, and added larger latency buckets
Exposed shuffle reader parallelism as a config param
=> VTX-4537: flight service update and more

Cargo.toml, ballista/core/Cargo.toml, ballista/core/src/async_reader/mod.rs, ballista/core/src/execution_plans/shuffle_reader.rs, ballista/executor/Cargo.toml
- Switched to async stream reader for local files
- use channel semaphore instead of an external one
=> VTX-4537: switch to async stream reader for local files, remove semaphore

Cargo.toml
[VTX-4270]
Backport fix from upstream DataFusion: https://github.com/apache/arrow-datafusion/pull/8552/files
[VTX-4270]: https://coralogix.atlassian.net/browse/VTX-4270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update datafusion version to include backported fix

ballista/core/proto/ballista.proto, ballista/core/src/client.rs, ballista/core/src/execution_plans/shuffle_reader.rs, ballista/core/src/serde/generated/ballista.rs, ballista/core/src/serde/mod.rs, ballista/scheduler/benches/scheduler_events.rs, ballista/scheduler/src/bin/main.rs, ballista/scheduler/src/cluster/kv.rs, ballista/scheduler/src/cluster/mod.rs, ballista/scheduler/src/planner.rs, ballista/scheduler/src/scheduler_process.rs, ballista/scheduler/src/scheduler_server/grpc.rs, ballista/scheduler/src/scheduler_server/mod.rs, ballista/scheduler/src/standalone.rs, ballista/scheduler/src/state/execution_graph.rs, ballista/scheduler/src/state/execution_graph/execution_stage.rs, ballista/scheduler/src/state/execution_graph_dot.rs, ballista/scheduler/src/state/mod.rs, ballista/scheduler/src/state/task_manager.rs, ballista/scheduler/src/test_utils.rs
Introducing ballista client with an upper limit for the number of requests (per executor), even if we have N open files per flight service, we don't have any limitation on the number of requests sent by the client itself, so some clients may consume all capacity available on a service. By introducing a cap, I'm trying to make the ballista client more respectful of other kids on a block.
The proper number still needs to be selected empirically. In general, it should improve p99 latency, but decrease p95 (for how much?)
=> VTX-4537: max request per ballista client

ballista/core/src/async_reader/mod.rs, ballista/core/src/client.rs, ballista/core/src/execution_plans/mod.rs, ballista/core/src/execution_plans/shuffle_reader.rs, ballista/core/src/execution_plans/shuffle_writer.rs, ballista/core/src/lib.rs, ballista/core/src/permit_stream/mod.rs, ballista/core/src/utils.rs, ballista/executor/src/flight_service.rs, ballista/executor/src/replicator/mod.rs
Giving a permit per stream and dropping it only when the stream ends. This way we control steam parallelism.
Few places:
- number of streams per client
- number of streams per shuffle reader fetch cycle 
- number of streams for flight_service
=> VTX-4537: control the real amount of concurrent streams
